# Generated by Django 4.2.5 on 2025-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
