# Generated by Django 5.1.6 on 2025-03-30 06:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, verbose_name='カテゴリー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='ユーザー名')),
                ('first_name', models.CharField(max_length=150, verbose_name='名字')),
                ('last_name', models.CharField(max_length=150, verbose_name='名前')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255, verbose_name='店舗名')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像')),
                ('detail', models.TextField(max_length=255, verbose_name='詳細')),
                ('business_day', models.CharField(max_length=255, verbose_name='営業日')),
                ('bussiness_hour', models.CharField(max_length=255, verbose_name='営業時間')),
                ('p_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('tel', models.CharField(max_length=15, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=255, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.shop', verbose_name='店舗')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteShop',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.shop', verbose_name='店舗')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.shop', verbose_name='店舗')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.shop', verbose_name='店舗')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'date', 'start_time'), name='unique_reservation')],
            },
        ),
    ]
