from django.urls import path
from uuid import UUID
from . import views
from .views import SignUpView, PasswordResetDoneView
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LoginView,
)

app_name = "crud"
urlpatterns = [
    path("", views.TopView.as_view(), name="top"),
    path("member_index/", views.MemberIndexView.as_view(), name="member_index"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password_change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("admin_index/", views.AdminIndexView.as_view(), name="admin_index"),
    path("mypage/", views.MypageView.as_view(), name="mypage"),
    path("shop/", views.ShopListView.as_view(), name="shop_list"),
    path("shop/<int:pk>/", views.ShopDetailView.as_view(), name="shop_detail"),
    path("shop/create/", views.ShopCreateView.as_view(), name="shop_create"),
    path("shop/update/<int:pk>/", views.ShopUpdateView.as_view(), name="shop_update"),
    path("shop/delete/<int:pk>/", views.ShopDeleteView.as_view(), name="shop_delete"),
    path("category/", views.CategoryListView.as_view(), name="category_list"),
    path("category/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail"),
    path("category/create/", views.CategoryCreateView.as_view(), name="category_create"),
    path("category/update/<int:pk>/", views.CategoryUpdateView.as_view(), name="category_update"),
    path("category/delete/<int:pk>/", views.CategoryDeleteView.as_view(), name="category_delete"),
    path("reservation/", views.ReservationListView.as_view(), name="reservation_list"),
    path("reservation/<int:pk>/", views.ReservationDetailView.as_view(), name="reservation_detail"),
    path("reservation/create/", views.ReservationCreateView.as_view(), name="reservation_create"),
    path("reservation/update/<int:pk>/", views.ReservationUpdateView.as_view(), name="reservation_update"),
    path("reservation/delete/<int:pk>/", views.ReservationDeleteView.as_view(), name="reservation_delete"),
    path("review/", views.ReviewListView.as_view(), name="review_list"),
    path("review/<int:pk>/", views.ReviewDetailView.as_view(), name="review_detail"),
    path("review/create/", views.ReviewCreateView.as_view(), name="review_create"),
    path("review/update/<int:pk>/", views.ReviewUpdateView.as_view(), name="review_update"),
    path("review/delete/<int:pk>/", views.ReviewDeleteView.as_view(), name="review_delete"),
    path("favorite/", views.FavoriteShopListView.as_view(), name="favorite_shop_list"),
    path("favorite/create/", views.FavoriteShopCreateView.as_view(), name="favorite_shop_create"),
    path("favorite/delete/<int:pk>/", views.FavoriteShopDeleteView.as_view(), name="favorite_shop_delete"),
    path("favorite/<int:pk>/", views.FavoriteShopDetailView.as_view(), name="favorite_shop_detail"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("user/update/<int:pk>/", views.UserUpdateView.as_view(), name="user_update"),
    path("user/delete/<int:pk>/", views.UserDeleteView.as_view(), name="user_delete"),
    path("user/create/", views.UserCreateView.as_view(), name="user_create"),
    path("user/list/", views.UserListView.as_view(), name="user_list"),
    path("user/<int:pk>/delete/", views.UserDeleteView.as_view(), name="user_delete"),
    path("user/<int:pk>/update/", views.UserUpdateView.as_view(), name="user_update"),
    path("user/<int:pk>/detail/", views.UserDetailView.as_view(), name="user_detail"),
    path("user/cancel/<int:pk>/", views.UserCancelView.as_view(), name="user_cancel"),
    path("user/cancel/<uuid:pk>/", views.UserCancelView.as_view(), name="user_cancel"),
    path('completion/', views.CompletionView.as_view(), name='completion'),  # 完了ページのURL
]